AWSTemplateFormatVersion: "2010-09-09"
Description: "Create AWS SimpleAD"

Resources:
  myDirectory:
    Type: AWS::DirectoryService::SimpleAD
    Properties:
      Name: ws.test.net
      Password: PutPassHereSimpleAD20!8
      Size: Small
      VpcSettings:
        SubnetIds:
          - !ImportValue APPsubnet1
          - !ImportValue APPsubnet2
        VpcId: !ImportValue WS-Vpc
