AWSTemplateFormatVersion: "2010-09-09"
Description: "Create a VPC with"

Parameters:
  CIDR:
    Type: String
    Description: "Enter a valid 10.x.x.x Private IP CIDR block"
    Default: "10.66.0.0/16"
  SubnetTiers:
    Type: String
    Description: "Number of tiers you would like to use, default is 2"
    Default: 2
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref CIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
       - Key: Name
         Value: !Join ["", ["VPC-", !Ref "AWS::Region"]]
  DMZnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.66.11.0/24
      AvailabilityZone:
        Fn::Select:
        - 0
        - Fn::GetAZs: ''
      Tags:
        - Key: Name
          Value: "DMZnet1"
  DMZnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.66.12.0/24
      AvailabilityZone:
        Fn::Select:
        - 1
        - Fn::GetAZs: ''
      Tags:
        - Key: Name
          Value: "DMZnet2"
  APPnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.66.21.0/24
      AvailabilityZone:
        Fn::Select:
        - 0
        - Fn::GetAZs: ''
      Tags:
        - Key: Name
          Value: "APPnet1"
  APPnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.66.22.0/24
      AvailabilityZone:
        Fn::Select:
        - 1
        - Fn::GetAZs: ''
      Tags:
        - Key: Name
          Value: "APPnet2"
  InternetGateway:
   Type: "AWS::EC2::InternetGateway"
   Properties:
    Tags:
     - Key: Application
       Value: !Ref "AWS::StackName"
     - Key: Name
       Value: "VPC-IG"
  GatewayToInternet:
   Type: "AWS::EC2::VPCGatewayAttachment"
   Properties:
    VpcId: !Ref VPC
    InternetGatewayId: !Ref InternetGateway
  PublicRouteTable:
   Type: AWS::EC2::RouteTable
   Properties:
    VpcId: !Ref VPC
    Tags:
     - Key: Application
       Value: !Ref "AWS::StackName"
     - Key: Name
       Value: Public Access
  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: GatewayToInternet
    Properties:
     RouteTableId: !Ref PublicRouteTable
     DestinationCidrBlock: "0.0.0.0/0"
     GatewayId: !Ref InternetGateway
  PublicRouteAssociation1:
   Type: AWS::EC2::SubnetRouteTableAssociation
   Properties:
    RouteTableId: !Ref PublicRouteTable
    SubnetId: !Ref DMZnet1
  PublicRouteAssociation2:
   Type: AWS::EC2::SubnetRouteTableAssociation
   Properties:
    RouteTableId: !Ref PublicRouteTable
    SubnetId: !Ref DMZnet2
